### PR TITLE
Fix: Prevent duplicate api calls on text filtering

### LINKED ISSUE #1131: [BUG] Duplicated API calls from frontend on text filtering
I have now over 400 documents in my paperless installation. Nearly 100 documents of them are fairly large (200 pages color).

Paperless-ngx V1.7.1 with postgres

When typing ~~slowly~~ at normal speed (not Superman fast...) some long search keyword into the "title and content" field at "documents" it seems that there is for every letter a new SELECT statement transferred to the postgres instance. This leads to a "flickering" effect of matching thumbnails/documents. It shows the new result for half a second, jumps back to the origin view, show another new thumbnail preview, jumps back to the origin view and so on. It takes couple of seconds when finally the final result view for the actual search keyword is found and "flickering" ends.

#############
It already does have a debounce, thats not really the same issue.

_Originally posted by @shamoon in https://github.com/paperless-ngx/paperless-ngx/discussions/288#discussioncomment-2354915_

#############

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This PR attempts to address the fact that text filtering causes duplicate calls to the API from the frontend. See videos before / after.

https://user-images.githubusercontent.com/4887959/173458948-502d718e-de73-4f5a-b531-e3a38201976d.mov

https://user-images.githubusercontent.com/4887959/173458954-b67a32b1-1cfa-4e8f-a56d-4b6c3e5c3b5b.mov

Fixes #1131

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

File: src-ui/src/app/data/filter-rule.ts [hunk 1]
```diff
@@ -25,6 +25,34 @@ export function isFullTextFilterRule(filterRules: FilterRule[]): boolean {
...
+      return (
+        filterRulesB.find(
+          (fri) => fri.rule_type == rule.rule_type && fri.value == rule.value
+        ) == undefined
+      )
+    })
+
+    if (!modified) {
+      // only check other direction if we havent already determined is modified
+      modified = filterRulesB.some((rule) => {
```
Comment (bauerj) [inline src-ui/src/app/data/filter-rule.ts:46]: Why would this be necessary?

If we have two sets a and b of the same length and all elements of a are in b then all elements of b must be in a.

Or would it be possible to have duplicate filter rules in the list?

**Review by bauerj — COMMENTED** [review]
Most of the code looks like it makes sense. Then again, I never worked with Angular. So not sure if I should review. I will test this however.

File: src-ui/src/app/data/filter-rule.ts (hunk 1 above)
Comment (shamoon) [reply src-ui/src/app/data/filter-rule.ts:46]: Yea I had this thought. Not that I actually sat down to test it but I think youre right that this if will never be reached, unless there are dupes. Still seems no real cost to leaving it "just in case". This function has been around for a while and basically moved from elsewhere in this PR, I didnt modify the logic.

Comment (shamoon) [reply src-ui/src/app/data/filter-rule.ts]: Yea lets ditch it, good catch!

Comment (bauerj) [reply src-ui/src/app/data/filter-rule.ts]: Great, thanks!

It probably won't have a noticeable performance impact with few filter rules but in the default case where the rules did not change, it would have always compared twice.
