### PR TITLE
Fix: Make missing environment from file files informational only

### LINKED ISSUE #2367: [BUG] env-from-file.sh breaks usage of COMPOSE_FILE
### Description

The paperless webserver is not starting up when the docker compose specific variable COMPOSE_FILE is used.
My Paperless compose file is named 'paperless.yml'. As I don't want to specify this explicitly every time when I run docker compose commands, I have set COMPOSE_FILE=paperless.yml in my .env file.

env-from-file.sh introduced with 06c6f33 breaks this and the webserver won't start because it can't find 'paperless.yml'.

I think this happens, because before this change, only certain environment variables were checked and now **all** variables are checked.

### Steps to reproduce

1. Name compose file something other than 'docker-compose.yml'
2. Specify environment variable 'COMPOSE_FILE' to use the right compose file
3. Start compose file and see webserver logs

### Webserver logs

```bash
Paperless-ngx docker container starting...
Installing languages...
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists...
Package tesseract-ocr-deu already installed!
Package tesseract-ocr-eng already installed!
File paperless.yml doesn't exist
Paperless-ngx docker container starting...
Installing languages...
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists...
Package tesseract-ocr-deu already installed!
Package tesseract-ocr-eng already installed!
File paperless.yml doesn't exist
```

### Browser logs

_No response_

### Paperless-ngx version

1.11.3

### Host OS

Debian 10

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Two changes to how setting environment from file contents works.

1. Only look at variables matching `PAPERLESS_*_FILE`
2. Make a missing file non-fatal, in case there's a `*_FILE` variable which isn't 

Fixes #2367

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

File: docker/env-from-file.sh [hunk 1]
```diff
@@ -32,8 +32,7 @@ do
 			export "${non_file_env_name}"="${val}"
 
 		else
-			echo "File ${env_value} doesn't exist"
-			exit 1
+			echo "File ${env_value} referenced ${env_name} by doesn't exist"
```
Comment (shamoon) [inline docker/env-from-file.sh:35]: Think this is a typo =)

**Review by shamoon — APPROVED** [review]
Cool thanks!

File: docker/env-from-file.sh (hunk 1 above)
Comment (stumpylog) [reply docker/env-from-file.sh]: Indeed.  Too early.

**Review by shamoon — APPROVED** [review]
