### PR TITLE
Fix: catch sessionStorage errors for large documents

### LINKED ISSUE #6144: [BUG] 404 on "Open document" right after import
### Description

Here a screencast:
[Screencast from 2024-03-20 09-08-52.webm](https://github.com/paperless-ngx/paperless-ngx/assets/6617661/6a0f8b3f-9c7b-43ac-9b1f-68b5a1ca331a)

Network tab in browser dev tools
Screenshot from 2024-03-20 09-38-27

and the sample document:
[7mb.pdf](https://github.com/paperless-ngx/paperless-ngx/files/14663554/7mb.pdf)

### Steps to reproduce

Import attached sample PDF by drag-and-drop, wait for paperless to digest it and then click on "Open document" in the alert box on the dashboard.
Briefly, the edit page is displayed with a loading spinner where the PDF itself would be shown.
Then, I get redirected to /404.
Clicking "Go to dashboard" does bring me back to the dashboard and on the left under "open documents" I can click on the newly imported document and everything works. I do have to wait a bit for the PDF to display though, since it is big.

### Webserver logs

```bash
[info][2024-03-20 08:21:55,598] [INFO] [paperless.consumer] Consuming 7mb.pdf
[info][2024-03-20 08:22:08,399] [WARNING] [ocrmypdf._pipeline] This PDF is marked as a Tagged PDF. This often indicates that the PDF was generated from an office document and does not need OCR. PDF pages processed by OCRmyPDF may not be tagged correctly.
[info][2024-03-20 08:22:08,672] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:08,685] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:08,685] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
...
[info][2024-03-20 08:22:09,474] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,474] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,475] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,475] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,476] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,476] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:10,246] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[info][2024-03-20 08:22:23,114] [INFO] [ocrmypdf.optimize] Image optimization did not improve the file - optimizations will not be used
[info][2024-03-20 08:22:26,533] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 0.95 savings: -5.1%
[info][2024-03-20 08:22:26,534] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.36 savings: 26.5%
[info][2024-03-20 08:22:26,715] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
[info][2024-03-20 08:23:20,661] [INFO] [paperless.consumer] Document 2024-03-20 7mb consumption finished
[info][2024-03-20 08:23:21,044] [INFO] [celery.app.trace] Task documents.tasks.consume_file[31376673-49c2-431b-acec-d270c892337d] succeeded in 85.8514666430001s: 'Success. New document id 6 created'
```

### Browser logs

```bash
nothing in the console
```

### Paperless-ngx version

2.6.2

### Host OS

Archlinux

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

_No response_

### Other

"Use PDF viewer provided by the browser" not checked.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This certainly seems to be an edge case since no one's reported it before because it comes down to extremely large documents (example is 7.7mb of purely text, i.e. 986k words / 6.6million characters, i.e. perhaps absurd) which exceed the browser [storage quota](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#how_much_data_can_be_stored). So Im fine (obviously) with the fix here which is just to catch the error and continue along.

Closes #6144

## Type of change

- [x] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

File: src-ui/setup-jest.ts [hunk 1]
```diff
@@ -76,7 +76,10 @@ const mock = () => {
   let storage: { [key: string]: string } = {}
   return {
     getItem: (key: string) => (key in storage ? storage[key] : null),
-    setItem: (key: string, value: string) => (storage[key] = value || ''),
+    setItem: (key: string, value: string) => {
+      if (value.length > 1000000) throw new Error('localStorage overflow')
```
Comment (pustekuchen91) [inline src-ui/setup-jest.ts:80]: const maxLocalStorageSize = 1000000;
if (value.length > maxLocalStorageSize) throw new Error('localStorage overflow')

Comment (shamoon) [reply src-ui/setup-jest.ts:80]: Thanks but this is purely for testing so that change isn't very useful I think

**Review by stumpylog — APPROVED** [review]
Certainly an edge case
